# Generated by Django 4.2.23 on 2025-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
