# Generated by Django 4.2.23 on 2025-07-20 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0004_alter_projectinfo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
