# Generated by Django 4.2.23 on 2025-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0005_projectinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='incomstatement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
