# Generated by Django 4.2.23 on 2025-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0006_alter_projectinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
