# Generated by Django 4.2.23 on 2025-07-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0008_alter_projectinfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='date',
        ),
    ]
