# Generated by Django 4.2.23 on 2025-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0003_trialinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialinfo',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
