# Generated by Django 4.2.23 on 2025-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0004_trialinfo_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
