# Generated by Django 4.2.23 on 2025-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0006_trialinfo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='ledgerbalance',
            field=models.FloatField(default=float),
        ),
    ]
