# Generated by Django 4.2.23 on 2025-06-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0004_alter_projectinfo_project'),
        ('Projet_Page', '0007_datainfo_ledgerbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pdfs', to='Home_Page.projectinfo')),
            ],
        ),
    ]
