# Generated by Django 4.2.23 on 2025-06-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0004_alter_projectinfo_project'),
        ('Projet_Page', '0008_questionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='pdf',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Home_Page.projectinfo'),
        ),
    ]
