# Generated by Django 4.2.23 on 2025-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0010_alter_questionpaper_pdf_alter_questionpaper_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='ledgerorder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
