# Generated by Django 4.2.23 on 2025-07-14 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0010_alter_questionpaper_pdf_alter_questionpaper_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
