# Generated by Django 4.2.23 on 2025-07-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0011_datainfo_ledgerorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='ledgerorder',
        ),
    ]
