# Generated by Django 4.2.23 on 2025-07-15 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0011_datainfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
