# Generated by Django 4.2.23 on 2025-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0012_remove_datainfo_ledgerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
