# Generated by Django 4.2.23 on 2025-07-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0012_codeinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialinfo',
            name='Account_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trialinfo',
            name='sheet',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
