# Generated by Django 4.2.23 on 2025-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0013_trialinfo_account_type_trialinfo_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialinfo',
            name='Account_type',
        ),
        migrations.AddField(
            model_name='trialinfo',
            name='account_type',
            field=models.CharField(default='Choose...', max_length=100),
        ),
    ]
