# Generated by Django 4.2.23 on 2025-07-14 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0013_datainfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
