# Generated by Django 4.2.23 on 2025-07-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0014_alter_datainfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='date',
        ),
    ]
