# Generated by Django 4.2.23 on 2025-07-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0014_remove_trialinfo_account_type_trialinfo_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialinfo',
            name='account_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trialinfo',
            name='sheet',
            field=models.CharField(default='Choose...', max_length=100),
        ),
    ]
