# Generated by Django 4.2.23 on 2025-07-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0015_alter_trialinfo_account_type_alter_trialinfo_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialinfo',
            name='account_type',
            field=models.CharField(max_length=100),
        ),
    ]
