# Generated by Django 4.2.23 on 2025-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0017_remove_datainfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
