# Generated by Django 4.2.23 on 2025-07-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0017_alter_trialinfo_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialinfo',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='trialinfo',
            name='sheet',
        ),
    ]
