# Generated by Django 4.2.23 on 2025-07-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0018_datainfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='date',
            field=models.DateTimeField(blank=True, default='01/01/2000', null=True),
        ),
    ]
