# Generated by Django 4.2.23 on 2025-07-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0018_remove_trialinfo_account_type_remove_trialinfo_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialinfo',
            name='account_type',
            field=models.CharField(default='Choose...', max_length=100),
        ),
        migrations.AddField(
            model_name='trialinfo',
            name='sheet',
            field=models.CharField(default='Choose...', max_length=100),
        ),
    ]
