# Generated by Django 4.2.23 on 2025-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0019_alter_datainfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='date',
            field=models.DateTimeField(blank=True, default='2025-07-14', null=True),
        ),
    ]
