# Generated by Django 4.2.23 on 2025-07-14 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet_Page', '0020_alter_datainfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
